sudo: required
dist: trusty
language: generic

before_install:
   - sudo apt-get update
   - sudo apt-get install -y --no-install-recommends moreutils dblatex asciidoc texlive-lang-german calibre calibre-bin python-sip epubcheck

script:
   - make verbose
   - make test

#after_failure:
#   - sudo apt-get install libxml2-utils
#   - make xmllint

notifications:
  irc: irc.lugs.ch#kivamon
